# Generated by Django 4.1.5 on 2023-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.IntegerField(max_length=10),
        ),
    ]
