# Generated by Django 4.1.5 on 2023-02-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='zip',
            new_name='Zip',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pasword',
            new_name='password',
        ),
    ]
