# Generated by Django 4.1.5 on 2023-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
