# Generated by Django 4.1.5 on 2023-02-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='password',
            new_name='name',
        ),
    ]
